### ISSUE TITLE
Long.MIN_VALUE value should throw Exception in UnivariatePolynomialZ64#negate()

### ISSUE THREAD

**Issue by axkr** [PoslavskySV/rings#42]
`Long.MIN_VALUE` value should throw Exception in `UnivariatePolynomialZ64#negate()`, otherwise the following overflow won't be detected:
```
  public static void main(String[] args) {
    System.out.println(Long.MIN_VALUE * -1L);
  }

```

**Comment by PoslavskySV** [comment]
Thanks for reporting this!
