### ISSUE TITLE
Polynomial base check

### ISSUE THREAD

**Issue by junwei-wang** [PoslavskySV/rings#48]
https://github.com/PoslavskySV/rings/blob/b438f93a751386295d44d750b74191222aaa221b/rings/src/main/java/cc/redberry/rings/poly/univar/UnivariatePolynomial.java#L1361

If poly1 is in Z_p1[x], poly2 is in Z_p2[x], 
then poly1 x poly2 is in Z_p1[x] and poly2 x poly1 is in Z_p2[x]

**Comment by PoslavskySV** [comment]
Yes, that is. Since, it is not supposed to multiply polynomials from different rings, it may be better to throw exception when p1 != p2 (this is already so for multivariate polynomials). I'll add the exception for univariate polynomials in next release. Thanks!

**Comment by junwei-wang** [comment]
Could you pls also support a feature, let *ring*.*multiply*(*poly1*, *poly2*)
do the operation with the *ring* base, instead of with the base of *poly1*
and *poly2*.

**Comment by junwei-wang** [comment]
Or you can add a feature switch a polynomial from its base to another.

**Comment by PoslavskySV** [comment]
You can switch polynomial base to another like this:

```java
// two different base rings
IntegersZp zp1 = Zp(3), zp2 = Zp(17);
UnivariatePolynomial<BigInteger>
        poly1 = UnivariatePolynomial.create(zp1, 1, 2, 3),   // in Z_p1[x]
        poly2 = UnivariatePolynomial.create(zp2, 4, 5, 6);   // in Z_p2[x]

//switch the base ring
UnivariatePolynomial<BigInteger> poly3 = poly2.setRing(zp1);
assert poly3.ring.equals(poly1.ring);
// you can also check the method setRingUnsafe which doesn't perform the copy

//or just
UnivariatePolynomial<BigInteger> samePoly3 = poly2.setRing(poly1.ring);
assert poly3.equals(samePoly3);

// or via polynomial ring
UnivariateRing<UnivariatePolynomial<BigInteger>>
        zp1x = UnivariateRing(zp1),
        zp2x = UnivariateRing(zp2);
UnivariatePolynomial<BigInteger> againSamePoly3 = zp1x.valueOf(poly2);
assert poly3.equals(againSamePoly3);
```

In the next release I can also add method like `Ring.castMultiply(a, b)` (for plus, minus as well) which will look like:

```java
interface Ring<E> ... { 

    default E castMultiply(E a, E, b) {
         return multiply(valueOf(a), valueOf(b));
    }
}
```
