### ISSUE TITLE
Avoid sun.misc 

### ISSUE THREAD

**Issue by tordr** [PoslavskySV/rings#53]
Just downloaded the software and added it as a Maven project. The compiler gave a set of errors and warnings. All of them because of the use of sun.misc classes in the code. I am using java version 10.0.2.

I do not know how easy or difficult it would be to remove/rewrite these parts of the code.

**Comment by PoslavskySV** [comment]
Hi! 

Just tried with JDK 11: created new Maven project, added  rings 2.5.2 and everything worked just fine --- no any problems with `sun.misc`. How can I reproduce your problem?

**Comment by tordr** [comment]
The problem seems to be on my side. When I start a new project using the maven build I sun.misc is not supported. When I add sun.misc.unsafe to my other project it does not complain when compiling the code.

For reference I am using Intellij IDEA 2018.2.4
