### ISSUE TITLE
Cached modular inverses

### ISSUE THREAD

**Issue by michiexile** [PoslavskySV/rings#57]
For relatively small primes (say < 65k or so), precalculating all inverses and storing them in a lookup table is often faster (amortized over a long calculation in the same finite field) than recalculating each inverse whenever it is needed.

**Comment by PoslavskySV** [comment]
Thanks for the suggestion! I'm not sure that currently this is really needed, but at some point I'll certainly return to this.

**Comment by michiexile** [comment]
I'm looking to adopt the library for a large persistent homology project
I'm planning - and for that, there will be sufficiently many computations
within a single finite field that using cached inverses is critical to get
useful performance.

**Comment by PoslavskySV** [comment]
I see. I've created a small PR https://github.com/PoslavskySV/rings/pull/59 which addresses this issue. Is that what you need?
