### ISSUE TITLE
PolynomialExtendedGCD unit tests

### ISSUE THREAD

**Issue by axkr** [PoslavskySV/rings#63]
With this commit I'm using SymjaRings.PolynomialExtendedGCDOverQ

```
			IExpr temp = SymjaRings.PolynomialExtendedGCDOverQ(expr1, expr2, x);
			if (temp.isPresent()) {
				return temp;
			}
```
- https://github.com/axkr/symja_android_library/commit/355d9889642f71d56123cd7eb07ea837bce8b01b

I found the following unit test problems:

```
>> PolynomialExtendedGCD((x - 1)^2*(x - 2)^2, (x - 1)*(x^2 - 3), x)
```

returns `{2-2*x,{-19-11*x,26-36*x+11*x^2}}`

but expected is: `{-1+x,{1/2*(19+11*x),1/2*(-26+36*x-11*x^2)}}`

and

```
>> PolynomialExtendedGCD(3+3*x^3,3+3*x^3,x)
```

returns `{1,{0,3+3*x^3}}`

but expected is: `{1+x^3,{0,1/3}}`

**Comment by PoslavskySV** [comment]
The first answer is correct, while in the second case - you are right - it was a bug for case when a == b. I've just fixed it in the latest commit.  Thanks!

**Comment by axkr** [comment]
Though the first answer is correct it's different from the `PolynomialGCD` results.

```
>> PolynomialGCD((x - 1)^2*(x - 2)^2, (x - 1)*(x^2 - 3))

-1+x
```

But the `PolynomialExtendedGCD` returns `2-2*x` for the gcd?

**Comment by PoslavskySV** [comment]
Yes, and that is done on purpose. The thing is that computations are always _much_ faster when performed in `Z[x]` than in `Q[x]`.  So in this example GCD is simplified in `Z[x]`, as well as XGCD (the common _integer_ content of xgcd is reduced). If force the GCD of XGCD to be monic or primitive in the corresponding Euclidean domain, you will have Bezout's multipliers with rationals, which is very undesirable (_especially_ when working in `Q(alpha)[x]`).

**Comment by PoslavskySV** [comment]
Just released the fix in maven in v2.5.5.

**Comment by axkr** [comment]
Thanks I changed the pom.xml.

I tested `PolynomialExtendedGCD(3+3*x^3,3+3*x^3,x)` with Maple and WolframAlpha

- https://www.wolframalpha.com/input/?i=PolynomialExtendedGCD%283%2B3*x%5E3%2C3%2B3*x%5E3%2Cx%29

both return `{1+x^3,{0,1/3}}`

**Comment by PoslavskySV** [comment]
Singular, for example, returns 
```
ring r = 0,(x),lp;
extgcd(3+3*x^3,3+3*x^3);
[1]:
   3x3+3
[2]:
   0
[3]:
   1
```
In general, if xGCD is `[g, a, b]` for `F[x]`, and `f` is a number from `F`, then `[f*g, f*a, f*b]` is also a correct xGCD triplet. So you can multiply all xGCD polynomials by the _same_ arbitrary non-zero number. This is why the result of xGCD is different in different CASs / libraries (but different only up to a numeric factor).
