### ISSUE TITLE
Invalid canonicalization of PolynomialFactorDecomposition

### ISSUE THREAD

**Issue by tueda** [PoslavskySV/rings#65]
If I understand correctly, `PolynomialFactorDecomposition<Poly>.canonical()` just sorts the factors and should not change the polynomial, but in the following case the result changes:
```scala
$ rings.repl
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Loading...
Running Ammonite Repl
Rings 2.5.5: efficient Java/Scala library for polynomial rings.
@ implicit val ring = MultivariateRing(Z, Array("x", "y"))
ring: MultivariateRing[IntZ] = MultivariateRing(Z, Array("x", "y"), GREVLEX)

@ val p = ring("x^3 + x^2*y")
p: MultivariatePolynomial[IntZ] = x^2*y+x^3

@ Factor(p)
res2: PolynomialFactorDecomposition[MultivariatePolynomial[IntZ]] = (x)^2*(y+x)

@ Factor(p).canonical()
res3: PolynomialFactorDecomposition[MultivariatePolynomial[IntZ]] = (x^2)^2*(y+x)

@ Factor(p).canonical().canonical()
res4: PolynomialFactorDecomposition[MultivariatePolynomial[IntZ]] = (x^4)^2*(y+x)
```

I guess in the following code `(x)^2` is expected to be translated to `(x^2)^1`

https://github.com/PoslavskySV/rings/blob/5227b1d23b5012ece5c4e123289fe1558c5d31d7/rings/src/main/java/cc/redberry/rings/poly/PolynomialFactorDecomposition.java#L73-L77

but indeed  `eTmp[i]` is not changed accordingly, leading to `(x^2)^2`.

**Comment by PoslavskySV** [comment]
That's a bug. Thanks for reporting! Will fix it today.

**Comment by PoslavskySV** [comment]
@tueda I've just made a release with the fix, it is now available from brew.

**Comment by tueda** [comment]
Thanks for your quick fix!
