### ISSUE TITLE
Freeze in polynomial factorization

### ISSUE THREAD

**Issue by tueda** [PoslavskySV/rings#70]
It seems that the following polynomial factorization never returns (or at least extremely slow):
```java
import cc.redberry.rings.bigint.BigInteger;
import cc.redberry.rings.poly.multivar.MultivariateFactorization;
import cc.redberry.rings.poly.multivar.MultivariatePolynomial;

var p = MultivariatePolynomial.parse("(x1-1)*(x2-1)*(x3-1)*(x4-1)");
var f = MultivariateFactorization.Factor(p);
```
Mathematica and FORM perform this factorization instantly, so it must not be time-consuming, I think.

**Comment by PoslavskySV** [comment]
Hi Takahiro! Thanks for reporting, I confirm that this is a bug. Easy to fix, will release new version on weekend, also will update to the recent Java and Scala versions.

**Comment by tueda** [comment]
Thank you for your prompt response! Good to hear that it is easy to fix.
